Feat/pomerium postgres ha
sighupio/fury-kubernetes-auth pull request #35
Opened 2024-11-14 09:58 UTC by alfonsofortunato

2024-11-14 10:11 UTC, ralgozino requested changes
I don't see the changes introduced in #34 please rebase with latest changes on main.

Also, CI is failing, you need to add the license headers to the new YAML files `postgres/kustomization.yaml` and `postgres/postgresql.yml`

2024-11-15 15:03 UTC, ralgozino requested changes

2024-11-15 15:03 UTC, ralgozino commented on katalog/pomerium/secrets/pomerium.example.env
> +
This env var is missing:
```suggestion
DATABROKER_STORAGE_TYPE=postgres
```

2024-11-15 15:03 UTC, ralgozino commented on katalog/pomerium/postgres/postgresql.yml
> +  postgres-password: "b29wOU9kOHV3ZWk2U29vQnVhaGFlZmF4"
should we ask for this password to the user os it safe to leave hard coded?

2024-11-18 08:41 UTC, alfonsofortunato commented on katalog/pomerium/secrets/pomerium.example.env
> +
It is in "config.example.env"

2024-11-18 14:23 UTC, ralgozino commented
IMO this PR should not be included as-is, Pomerium in HA is considerable slower, to the point that Hubble for example stops working and Grafana is painfully slow to use.

I don't know if is some misconfiguration or could be something on my test environment.

2025-03-05 10:12 UTC, closed without merging